version: '3.9'

services:
  server:
    build: .
    restart: on-failure
    ports:
      - '3000:3000'
  db:
    image: 'postgres'
    ports:
      - '4444:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'